import { AxiosResponseHeaders, RawAxiosResponseHeaders } from 'axios';
export interface IHttpClient {
    get(methodName: string, requestData: IRequestData): Promise<IResponse | IErrorResponse>;
    post(methodName: string, requestData: IRequestData): Promise<IResponse | IErrorResponse>;
    put(methodName: string, requestData: IRequestData): Promise<IResponse | IErrorResponse>;
    patch(methodName: string, requestData: IRequestData): Promise<IResponse | IErrorResponse>;
    delete(methodName: string, requestData: IRequestData): Promise<IResponse | IErrorResponse>;
    handlerRequestError(ex: any, serviceName: string, methodName: string): IErrorResponse;
}
export interface IRequestData {
    path: string;
    config?: IHeadersConfig;
    query?: any;
    body?: any;
}
export interface IResponse {
    isAxiosError?: boolean;
    message?: string;
    data: any;
    status: number;
    headers: RawAxiosResponseHeaders | AxiosResponseHeaders;
}
export interface IErrorResponse {
    isAxiosError?: boolean;
    message?: string;
    serviceName?: string;
    host?: string;
    method?: string;
    path?: string;
    url?: string;
    status?: number;
    statusText?: string;
    data?: any;
}
export interface IUserAuth {
    ip: string;
    id: string;
    name: string;
    email: string;
    accessType: string;
}
export interface IHeadersConfig {
    ['Accept-CH-Lifetime']?: string | number;
    ['cid']?: string | number;
    ['userAuth']?: IUserAuth | string;
    ['trackId']?: string | number;
    ['Accept-CH']?: string | number;
    ['Accept-Charset']?: string | number;
    ['Accept-Encoding']?: string | number;
    ['Accept-Language']?: string | number;
    ['Accept-Patch']?: string | number;
    ['Accept-Post']?: string | number;
    ['Accept-Ranges']?: string | number;
    ['Accept']?: string | number;
    ['Access-Control-Allow-Credentials']?: string | number;
    ['Access-Control-Allow-Headers']?: string | number;
    ['Access-Control-Allow-Methods']?: string | number;
    ['Access-Control-Allow-Origin']?: string | number;
    ['Access-Control-Expose-Headers']?: string | number;
    ['Access-Control-Max-Age']?: string | number;
    ['Access-Control-Request-Headers']?: string | number;
    ['Access-Control-Request-Method']?: string | number;
    ['Age']?: string | number;
    ['Allow']?: string | number;
    ['Alt-Svc']?: string | number;
    ['Authorization']?: string | number;
    ['Cache-Control']?: string | number;
    ['Clear-Site-Data']?: string | number;
    ['Connection']?: string | number;
    ['Content-Disposition']?: string | number;
    ['Content-DPR']?: string | number;
    ['Content-Encoding']?: string | number;
    ['Content-Language']?: string | number;
    ['Content-Length']?: string | number;
    ['Content-Location']?: string | number;
    ['Content-Range']?: string | number;
    ['Content-Security-Policy-Report-Only']?: string | number;
    ['Content-Security-Policy']?: string | number;
    ['Content-Type']?: string | number;
    ['Cookie']?: string | number;
    ['Cookie2']?: string | number;
    ['Cross-Origin-Embedder-Policy']?: string | number;
    ['Cross-Origin-Opener-Policy']?: string | number;
    ['Cross-Origin-Resource-Policy']?: string | number;
    ['Date']?: string | number;
    ['Device-Memory']?: string | number;
    ['Digest']?: string | number;
    ['DNT']?: string | number;
    ['Downlink']?: string | number;
    ['DPR']?: string | number;
    ['Early-Data']?: string | number;
    ['ECT']?: string | number;
    ['ETag']?: string | number;
    ['Expect-CT']?: string | number;
    ['Expect']?: string | number;
    ['Expires']?: string | number;
    ['Feature-Policy']?: string | number;
    ['Forwarded']?: string | number;
    ['From']?: string | number;
    ['Host']?: string | number;
    ['If-Match']?: string | number;
    ['If-Modified-Since']?: string | number;
    ['If-None-Match']?: string | number;
    ['If-Range']?: string | number;
    ['If-Unmodified-Since']?: string | number;
    ['Keep-Alive']?: string | number;
    ['Large-Allocation']?: string | number;
    ['Last-Modified']?: string | number;
    ['Link']?: string | number;
    ['Location']?: string | number;
    ['NEL']?: string | number;
    ['Origin']?: string | number;
    ['Pragma']?: string | number;
    ['Proxy-Authenticate']?: string | number;
    ['Proxy-Authorization']?: string | number;
    ['Public-Key-Pins-Report-Only']?: string | number;
    ['Public-Key-Pins']?: string | number;
    ['Range']?: string | number;
    ['Referer']?: string | number;
    ['Referrer-Policy']?: string | number;
    ['Retry-After']?: string | number;
    ['RTT']?: string | number;
    ['Save-Data']?: string | number;
    ['Sec-Fetch-Dest']?: string | number;
    ['Sec-Fetch-Mode']?: string | number;
    ['Sec-Fetch-Site']?: string | number;
    ['Sec-Fetch-User']?: string | number;
    ['Sec-WebSocket-Accept']?: string | number;
    ['Server-Timing']?: string | number;
    ['Server']?: string | number;
    ['Set-Cookie']?: string | number;
    ['Set-Cookie2']?: string | number;
    ['SourceMap']?: string | number;
    ['Strict-Transport-Security']?: string | number;
    ['TE']?: string | number;
    ['Timing-Allow-Origin']?: string | number;
    ['Tk']?: string | number;
    ['Trailer']?: string | number;
    ['Transfer-Encoding']?: string | number;
    ['Upgrade-Insecure-Requests']?: string | number;
    ['Upgrade']?: string | number;
    ['User-Agent']?: string | number;
    ['Vary']?: string | number;
    ['Via']?: string | number;
    ['Viewport-Width']?: string | number;
    ['Want-Digest']?: string | number;
    ['Warning']?: string | number;
    ['Width']?: string | number;
    ['WWW-Authenticate']?: string | number;
    ['X-Content-Type-Options']?: string | number;
    ['X-DNS-Prefetch-Control']?: string | number;
    ['X-Forwarded-For']?: string | number;
    ['X-Forwarded-Host']?: string | number;
    ['X-Forwarded-Proto']?: string | number;
    ['X-Frame-Options']?: string | number;
    ['X-XSS-Protection']?: string | number;
    ['x-spin-signature']?: string | number;
    ['x-spin-timestamp']?: string | number;
    ['origin']?: string;
    ['x-user-groups']?: string | number;
    ['x-user-id']?: string | number;
    ['x-user-username']?: string | number;
}
